# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@qq.com', max_length=254),
        ),
    ]
